#!/bin/sh
. /etc/profile
set -eu
JAVA=${JAVA_HOME:-/usr}/bin/java

exec "$JAVA" \
  -Dlogback.configurationFile=/opt/search/logback.xml \
  -jar /opt/search/search.jar \
  >> /var/log/search/search.log 2>&1
